# Generated by Django 5.2.1 on 2025-05-26 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.CharField(help_text="Model name", max_length=100)),
                (
                    "object_id",
                    models.CharField(
                        help_text="Primary key of the object", max_length=100
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, help_text="Changed data", null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Log",
                "verbose_name_plural": "Action Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["table", "object_id"],
                        name="auditlog_ac_table_d39953_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="auditlog_ac_user_id_e4e2ad_idx",
                    ),
                ],
            },
        ),
    ]
