# Generated by Django 5.2.1 on 2025-06-18 11:42

import shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Upload a product image (JPEG, PNG, max 1MB)",
                upload_to=shop.utils.product_image_path,
                validators=[shop.utils.validate_image],
            ),
        ),
    ]
